using Security.Models.Database;
using System;
using System.Collections.Generic;
using System.Text;

namespace Security.DAO
{
    /// <summary>
    /// Interface for the UserSecurityDAO
    /// </summary>
    public interface IUserSecurityDAO
    {
        #region UserItem

        /// <summary>
        /// Adds a user to the database
        /// </summary>
        /// <param name="item">The user item to add</param>
        /// <returns>The autogenerated primary key</returns>
        int AddUserItem(UserItem item);

        /// <summary>
        /// Updates a row in the user table
        /// </summary>
        /// <param name="item">The user item to be changed</param>
        /// <returns>True if the record was successfully updated</returns>
        bool UpdateUserItem(UserItem item);

        /// <summary>
        /// Deletes a row from the user table
        /// </summary>
        /// <param name="userId">The primary key for the user item to be deleted</param>
        void DeleteUserItem(int userId);

        /// <summary>
        /// Gets a row from the user table
        /// </summary>
        /// <param name="userId">The primary key of the user item to retrieve</param>
        /// <returns>A user item holding the data from the user table</returns>
        UserItem GetUserItem(int userId);

        /// <summary>
        /// Gets a row from the user table
        /// </summary>
        /// <param name="username">The username of the user item to retrieve</param>
        /// <returns>A user item holding the data from the user table</returns>
        UserItem GetUserItem(string username);

        /// <summary>
        /// Gets a list of rows from the user table
        /// </summary>
        /// <returns>A list of populate user items from the user table</returns>
        List<UserItem> GetUserItems();

        #endregion

        #region RoleItem

        /// <summary>
        /// Adds a role item to the role table
        /// </summary>
        /// <param name="item">The role item data to be added</param>
        /// <returns>The primary key of the new record</returns>
        int AddRoleItem(RoleItem item);

        /// <summary>
        /// Gets a list of all the role items in the role table
        /// </summary>
        /// <returns>List of role items</returns>
        List<RoleItem> GetRoleItems();

        #endregion        
    }
}
